POST http://localhost:8080/api/tasks/user/2
Content-Type: application/json

{
  "title": "Make a frontend"
}

###
PATCH http://localhost:8080/api/tasks/1/status?status=IN_PROGRESS

###
DELETE http://localhost:8080/api/tasks/1

###
GET http://localhost:8080/api/tasks/user/2

###
GET http://localhost:8080/api/tasks/1