
###
PATCH http://localhost:8080/api/tasks/8/status?status=IN_PROGRESS
Authorization: Bearer {{jwt_token}}

###
DELETE http://localhost:8080/api/tasks/7
Authorization: Bearer {{jwt_token}}

###
GET http://localhost:8080/api/tasks
Authorization: Bearer {{jwt_token}}



### Create Task
POST http://localhost:8080/api/tasks
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "title": "final testing with new user",
  "status": "COMPLETED",
  "priority": "MEDIUM"
}