POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name":"Muhammad rehan",
  "email":"rehan@gmail.com",
  "password": "12345678"
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name":"taha",
  "email":"taha@gmail.com",
  "password": "abc123"
}


###
POST http://localhost:8080/api/tasks/user/1
Content-Type: application/json

{
  "title": "Do 10 push ups"
}

###
GET http://localhost:8080/api/users/1

###
GET http://localhost:8080/api/users