POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name":"Muhammad rehan",
  "email":"rehan@gmail.com",
  "password": "12345678"
}

###
POST http://localhost:8080/api/users
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "name":"Akhyar ahmed",
  "email":"akhyar@gmail.com",
  "password": "akhyar123"
}

###
POST http://localhost:8080/api/users
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "name":"taha",
  "email":"taha@gmail.com",
  "password": "abc123"
}


###
GET http://localhost:8080/api/users/me
Authorization: Bearer {{jwt_token}}

###
GET http://localhost:8080/api/users
Authorization: Bearer {{jwt_token}}